#ifndef ENV_CLASSIFIER_H
#define ENV_CLASSIFIER_H

// Auto-generated by train.py -- do not edit by hand.
// Regenerate by re-running train.py after collecting new data.
//
// This is a decision tree trained with scikit-learn, exported as plain
// nested if/else C code. No ML library runs on the Arduino; this *is*
// the trained model, just expressed as comparisons instead of a Python
// object graph. Inference cost is at most 2 comparisons
// per call -- negligible on an 8-bit AVR.

enum EnvClass {
  BRIGHT_COOL,
  BRIGHT_WARM,
  DARK_COOL,
  DARK_WARM
};

EnvClass classify(float raw_thermistor, float raw_photoresistor, float dht_temp_c, float dht_humidity) {
  if (raw_photoresistor <= 123.5000f) {
    if (raw_thermistor <= 555.0000f) {
      return DARK_COOL;
    } else {
      return DARK_WARM;
    }
  } else {
    if (raw_photoresistor <= 809.0000f) {
      return BRIGHT_WARM;
    } else {
      return BRIGHT_COOL;
    }
  }
}

#endif
