"""
train.py -- trains a decision tree on the collected sensor dataset and
exports it as C code that can run directly on an Arduino UNO with no
external library dependency.

Usage:
    python train.py [dataset.csv] [--max-depth N] [--output tree.h]

Why export to C instead of running sklearn on-device: the UNO's ATmega328P
has no Python interpreter, no floating-point unit, and 2KB of RAM -- there
is no version of scikit-learn (or any ML framework) that fits. A trained
decision tree, however, is fundamentally just a sequence of comparisons
("if raw_thermistor < 500") ending in a label -- exactly the kind of thing
that compiles down to almost nothing in C. This script walks the trained
tree's internal structure and emits that comparison logic directly.
"""

import argparse
from pathlib import Path

import numpy as np
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

FEATURE_NAMES = ["raw_thermistor", "raw_photoresistor", "dht_temp_c", "dht_humidity"]


def load_dataset(path):
    import csv
    X, y = [], []
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            X.append([
                float(row["raw_thermistor"]),
                float(row["raw_photoresistor"]),
                float(row["dht_temp_c"]),
                float(row["dht_humidity"]),
            ])
            y.append(row["label"])
    return np.array(X), np.array(y)


def export_tree_to_c(tree, feature_names, class_names, function_name="classify"):
    """
    Walks an sklearn DecisionTreeClassifier's internal tree structure and
    emits equivalent nested if/else C code. sklearn exposes the trained
    tree via tree.tree_, where each node has a feature index, a threshold,
    and left/right child indices (-1 for leaf nodes, which instead carry
    a class value).
    """
    tree_ = tree.tree_
    lines = []

    def recurse(node, depth):
        indent = "  " * (depth + 1)
        if tree_.feature[node] != -2:  # -2 marks a leaf node in sklearn's tree_
            feature = feature_names[tree_.feature[node]]
            threshold = tree_.threshold[node]
            lines.append(f"{indent}if ({feature} <= {threshold:.4f}f) {{")
            recurse(tree_.children_left[node], depth + 1)
            lines.append(f"{indent}}} else {{")
            recurse(tree_.children_right[node], depth + 1)
            lines.append(f"{indent}}}")
        else:
            class_index = np.argmax(tree_.value[node])
            class_name = class_names[class_index]
            lines.append(f"{indent}return {class_name.upper()};")

    lines.append(f"EnvClass {function_name}(float raw_thermistor, float raw_photoresistor, "
                 f"float dht_temp_c, float dht_humidity) {{")
    recurse(0, 0)
    lines.append("}")
    return "\n".join(lines)


def generate_header(tree, feature_names, class_names):
    c_function = export_tree_to_c(tree, feature_names, class_names)

    enum_entries = ",\n  ".join(name.upper() for name in class_names)

    header = f"""#ifndef ENV_CLASSIFIER_H
#define ENV_CLASSIFIER_H

// Auto-generated by train.py -- do not edit by hand.
// Regenerate by re-running train.py after collecting new data.
//
// This is a decision tree trained with scikit-learn, exported as plain
// nested if/else C code. No ML library runs on the Arduino; this *is*
// the trained model, just expressed as comparisons instead of a Python
// object graph. Inference cost is at most {tree.get_depth()} comparisons
// per call -- negligible on an 8-bit AVR.

enum EnvClass {{
  {enum_entries}
}};

{c_function}

#endif
"""
    return header


def main():
    parser = argparse.ArgumentParser(description="Train a decision tree and export it to C for Arduino.")
    parser.add_argument("dataset", nargs="?", default="dataset.csv", help="Path to labeled CSV dataset")
    parser.add_argument("--max-depth", type=int, default=4,
                         help="Max tree depth (default 4 -- keeps inference and the generated C code small)")
    parser.add_argument("--output", default="tree.h", help="Output header file path")
    args = parser.parse_args()

    dataset_path = Path(args.dataset)
    if not dataset_path.exists():
        print(f"Dataset not found: {dataset_path}")
        return

    X, y = load_dataset(dataset_path)
    print(f"Loaded {len(X)} rows, {len(set(y))} classes: {sorted(set(y))}")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y
    )

    clf = DecisionTreeClassifier(max_depth=args.max_depth, random_state=42)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"\nTest accuracy: {acc:.1%}")
    print("\nClassification report:")
    print(classification_report(y_test, y_pred))
    print("Confusion matrix (rows = actual, cols = predicted):")
    labels_sorted = sorted(set(y))
    print("Labels order:", labels_sorted)
    print(confusion_matrix(y_test, y_pred, labels=labels_sorted))

    print("\nTree structure (for your own sanity-check / writeup):")
    print(export_text(clf, feature_names=FEATURE_NAMES))

    class_names = list(clf.classes_)
    header = generate_header(clf, FEATURE_NAMES, class_names)

    output_path = Path(args.output)
    output_path.write_text(header)
    print(f"\nWrote {output_path} -- copy this into your Arduino sketch folder.")


if __name__ == "__main__":
    main()
